# Generated by Django 5.2.4 on 2025-12-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='وثيقة إثبات (حصر ورثة/هوية)'),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم الكامل'),
        ),
        migrations.AddField(
            model_name='user',
            name='judge_license',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم رخصة القاضي'),
        ),
    ]
