# Generated by Django 5.2.6 on 2025-12-09 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_judge',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'JUDGE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clerks', to=settings.AUTH_USER_MODEL, verbose_name='القاضي المشرف'),
        ),
    ]
