# Generated by Django 5.2.6 on 2025-12-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_assigned_judge'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clerk_judge_status',
            field=models.CharField(choices=[('PENDING', 'بانتظار الموافقة'), ('APPROVED', 'مقبول'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=20, verbose_name='حالة الارتباط بالقاضي'),
        ),
    ]
