# Generated by Django 5.2.4 on 2026-01-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_clerk_judge_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deceased_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم المتوفى'),
        ),
    ]
