# Generated by Django 5.2.4 on 2026-02-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_deceased_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='relationship_to_deceased',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='صلة القرابة بالمتوفى'),
        ),
    ]
