# Generated by Django 5.2.4 on 2026-02-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_relationship_to_deceased'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], max_length=10, null=True, verbose_name='الجنس'),
        ),
    ]
