# Generated by Django 5.2.5 on 2026-03-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='previous_role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'مدير النظام'), ('JUDGE', 'قاضي'), ('CLERK', 'كاتب مساعد'), ('HEIR', 'وريث'), ('PUBLIC', 'مستخدم عام')], max_length=20, null=True, verbose_name='الدور السابق'),
        ),
    ]
