# Generated by Django 5.2.5 on 2026-03-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_previous_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='court_address',
            field=models.TextField(blank=True, null=True, verbose_name='العنوان الرسمي'),
        ),
        migrations.AddField(
            model_name='user',
            name='court_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم المحكمة/المنظمة'),
        ),
        migrations.AddField(
            model_name='user',
            name='official_stamp',
            field=models.ImageField(blank=True, null=True, upload_to='stamps/', verbose_name='الختم الرسمي'),
        ),
    ]
