# Generated by Django 5.2.12 on 2026-04-03 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_court_address_user_court_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='الرسالة / الملاحظة')),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 نجمة'), (2, '2 نجمتان'), (3, '3 نجوم'), (4, '4 نجوم'), (5, '5 نجوم')], null=True, verbose_name='التقييم')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تقييم وملاحظة',
                'verbose_name_plural': 'التقييمات والملاحظات',
                'ordering': ['-date_created'],
            },
        ),
    ]
