# Generated by Django 5.2.5 on 2026-03-13 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('notification_type', models.CharField(choices=[('REGISTRATION', 'طلب تسجيل جديد'), ('ROLE_CHANGE', 'تغيير في الصلاحيات'), ('SYSTEM', 'تنبيه نظام'), ('CASE_UPDATE', 'تحديث قضية')], default='SYSTEM', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تنبيه المدير',
                'verbose_name_plural': 'تنبيهات المدير',
                'ordering': ['-created_at'],
            },
        ),
    ]
