# Generated by Django 5.2.6 on 2026-03-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiqhBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الكتاب')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='المؤلف')),
                ('pdf_file', models.FileField(upload_to='fiqh_books/', verbose_name='ملف الكتاب (PDF)')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='صورة الغلاف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
            ],
            options={
                'verbose_name': 'كتاب فقهي',
                'verbose_name_plural': 'الكتب الفقهية',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
