# Generated by Django 5.2.4 on 2025-12-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='الوصف')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='القيمة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/', verbose_name='صورة الأصل')),
                ('asset_type', models.CharField(choices=[('REAL_ESTATE', 'عقار'), ('CASH', 'نقد'), ('STOCK', 'أسهم'), ('OTHER', 'أخرى')], default='OTHER', max_length=20, verbose_name='نوع الأصل')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=50, unique=True, verbose_name='رقم القضية')),
                ('status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('ACTIVE', 'نشطة'), ('COMPLETED', 'مكتملة')], default='PENDING', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='وصف الدين')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
            ],
        ),
        migrations.CreateModel(
            name='Deceased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المتوفى')),
                ('date_of_death', models.DateField(verbose_name='تاريخ الوفاة')),
                ('national_id', models.CharField(max_length=20, verbose_name='رقم الهوية')),
            ],
        ),
        migrations.CreateModel(
            name='Heir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('relationship', models.CharField(choices=[('HUSBAND', 'زوج'), ('WIFE', 'زوجة'), ('SON', 'ابن'), ('DAUGHTER', 'بنت'), ('FATHER', 'أب'), ('MOTHER', 'أم'), ('BROTHER', 'أخ شقيق'), ('SISTER', 'أخت شقيقة')], max_length=20, verbose_name='صلة القرابة')),
                ('gender', models.CharField(choices=[('MALE', 'ذكر'), ('FEMALE', 'أنثى')], max_length=10, verbose_name='الجنس')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='محجوب')),
            ],
        ),
    ]
