# Generated by Django 5.2.4 on 2025-12-02 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='judge',
            field=models.ForeignKey(limit_choices_to={'role': 'JUDGE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to=settings.AUTH_USER_MODEL, verbose_name='القاضي'),
        ),
        migrations.AddField(
            model_name='asset',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='cases.case', verbose_name='القضية'),
        ),
        migrations.AddField(
            model_name='debt',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='cases.case', verbose_name='القضية'),
        ),
        migrations.AddField(
            model_name='deceased',
            name='case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deceased', to='cases.case', verbose_name='القضية'),
        ),
        migrations.AddField(
            model_name='heir',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heirs', to='cases.case', verbose_name='القضية'),
        ),
        migrations.AddField(
            model_name='heir',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heir_records', to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم'),
        ),
    ]
