# Generated by Django 5.2.4 on 2025-12-02 18:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='clerk',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'CLERK'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clerked_cases', to=settings.AUTH_USER_MODEL, verbose_name='الكاتب المساعد'),
        ),
        migrations.AddField(
            model_name='case',
            name='is_ready_for_calculation',
            field=models.BooleanField(default=False, verbose_name='جاهزة للحساب'),
        ),
        migrations.AddField(
            model_name='case',
            name='session_link',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='رابط الجلسة'),
        ),
        migrations.AlterField(
            model_name='case',
            name='judge',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'JUDGE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judged_cases', to=settings.AUTH_USER_MODEL, verbose_name='القاضي'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('PENDING', 'بانتظار القاضي'), ('ASSIGNED_TO_JUDGE', 'مقبولة (عند القاضي)'), ('WITH_CLERK', 'عند الكاتب (إدخال البيانات)'), ('READY_FOR_CALCULATION', 'جاهزة للحساب'), ('COMPLETED', 'مكتملة')], default='PENDING', max_length=30, verbose_name='الحالة'),
        ),
        migrations.CreateModel(
            name='Will',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='وصف الوصية')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wills', to='cases.case', verbose_name='القضية')),
            ],
        ),
    ]
