# Generated by Django 5.2.6 on 2025-12-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_clerk_case_is_ready_for_calculation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='judge_acceptance_status',
            field=models.CharField(choices=[('PENDING', 'بانتظار القبول'), ('ACCEPTED', 'مقبولة'), ('REJECTED', 'مرفوضة')], default='PENDING', max_length=20, verbose_name='حالة قبول القاضي'),
        ),
    ]
