# Generated by Django 5.2.6 on 2025-12-11 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_case_judge_acceptance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_assets', to='cases.heir', verbose_name='مخصص لـ'),
        ),
        migrations.AddField(
            model_name='asset',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='مقفل (تم الاختيار)'),
        ),
        migrations.AddField(
            model_name='heir',
            name='acceptance_status',
            field=models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('ACCEPTED', 'موافق'), ('REJECTED', 'غير موافق')], default='PENDING', max_length=20, verbose_name='حالة القبول'),
        ),
        migrations.AddField(
            model_name='heir',
            name='allocation_description',
            field=models.TextField(blank=True, verbose_name='وصف القسمة (رسالة القاضي)'),
        ),
        migrations.AddField(
            model_name='heir',
            name='share_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الإرث %'),
        ),
        migrations.AddField(
            model_name='heir',
            name='share_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='قيمة النصيب'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('PENDING', 'بانتظار القاضي'), ('ASSIGNED_TO_JUDGE', 'مقبولة (عند القاضي)'), ('WITH_CLERK', 'عند الكاتب (إدخال البيانات)'), ('DATA_REVIEW', 'مراجعة البيانات (عند القاضي)'), ('READY_FOR_CALCULATION', 'جاهزة للحساب'), ('SESSION_ACTIVE', 'جلسة توزيع التركة جارية'), ('COMPLETED', 'مكتملة')], default='PENDING', max_length=30, verbose_name='الحالة'),
        ),
    ]
