# Generated by Django 5.2.5 on 2026-01-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_asset_assigned_to_asset_is_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_liquidated',
            field=models.BooleanField(default=False, verbose_name='تم التسييل/البيع'),
        ),
        migrations.AddField(
            model_name='asset',
            name='sold_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='سعر البيع الفعلي'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('عقار', 'عقار'), ('نقد', 'نقد'), ('أسهم', 'أسهم'), ('أخرى', 'أخرى')], default='أخرى', max_length=20, verbose_name='نوع الأصل'),
        ),
        migrations.AlterField(
            model_name='case',
            name='judge_acceptance_status',
            field=models.CharField(choices=[('بانتظار القبول', 'بانتظار القبول'), ('مقبولة', 'مقبولة'), ('مرفوضة', 'مرفوضة')], default='بانتظار القبول', max_length=20, verbose_name='حالة قبول القاضي'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('بانتظار القاضي', 'بانتظار القاضي'), ('مقبولة (عند القاضي)', 'مقبولة (عند القاضي)'), ('عند الكاتب (إدخال البيانات)', 'عند الكاتب (إدخال البيانات)'), ('مراجعة البيانات (عند القاضي)', 'مراجعة البيانات (عند القاضي)'), ('جاهزة للحساب', 'جاهزة للحساب'), ('جلسة توزيع التركة جارية', 'جلسة توزيع التركة جارية'), ('مكتملة', 'مكتملة')], default='بانتظار القاضي', max_length=30, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='heir',
            name='acceptance_status',
            field=models.CharField(choices=[('قيد الانتظار', 'قيد الانتظار'), ('موافق', 'موافق'), ('غير موافق', 'غير موافق')], default='قيد الانتظار', max_length=20, verbose_name='حالة القبول'),
        ),
        migrations.AlterField(
            model_name='heir',
            name='gender',
            field=models.CharField(choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], max_length=10, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='heir',
            name='relationship',
            field=models.CharField(choices=[('زوج', 'زوج'), ('زوجة', 'زوجة'), ('ابن', 'ابن'), ('بنت', 'بنت'), ('أب', 'أب'), ('أم', 'أم'), ('أخ شقيق', 'أخ شقيق'), ('أخت شقيقة', 'أخت شقيقة'), ('ابن ابن', 'ابن ابن'), ('بنت ابن', 'بنت ابن'), ('جد (أبو الأب)', 'جد (أبو الأب)'), ('جدة (أم الأب)', 'جدة (أم الأب)'), ('جدة (أم الأم)', 'جدة (أم الأم)'), ('أخ لأب', 'أخ لأب'), ('أخت لأب', 'أخت لأب'), ('أخ لأم', 'أخ لأم'), ('أخت لأم', 'أخت لأم'), ('ابن أخ شقيق', 'ابن أخ شقيق'), ('ابن أخ لأب', 'ابن أخ لأب'), ('عم شقيق', 'عم شقيق'), ('عم لأب', 'عم لأب'), ('ابن عم شقيق', 'ابن عم شقيق'), ('ابن عم لأب', 'ابن عم لأب')], max_length=50, verbose_name='صلة القرابة'),
        ),
    ]
