# Generated by Django 5.2.5 on 2026-01-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_asset_is_liquidated_asset_sold_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='judge_acceptance_status',
            field=models.CharField(choices=[('PENDING', 'بانتظار القبول'), ('ACCEPTED', 'مقبولة'), ('REJECTED', 'مرفوضة')], default='PENDING', max_length=20, verbose_name='حالة قبول القاضي'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('PENDING', 'بانتظار القاضي'), ('ASSIGNED_TO_JUDGE', 'مقبولة (عند القاضي)'), ('WITH_CLERK', 'عند الكاتب (إدخال البيانات)'), ('DATA_REVIEW', 'مراجعة البيانات (عند القاضي)'), ('READY_FOR_CALCULATION', 'جاهزة للحساب'), ('SESSION_ACTIVE', 'جلسة توزيع التركة جارية'), ('COMPLETED', 'مكتملة')], default='PENDING', max_length=30, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='heir',
            name='acceptance_status',
            field=models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('ACCEPTED', 'موافق'), ('REJECTED', 'غير موافق')], default='PENDING', max_length=20, verbose_name='حالة القبول'),
        ),
    ]
