# Generated by Django 5.2.5 on 2026-01-04 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_alter_case_judge_acceptance_status_alter_case_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeirAssetSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_intents', to='cases.asset', verbose_name='الأصل')),
                ('heir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='cases.heir', verbose_name='الوريث')),
            ],
            options={
                'verbose_name': 'رغبة اختيار أصل',
                'verbose_name_plural': 'رغبات اختيار الأصول',
                'unique_together': {('heir', 'asset')},
            },
        ),
    ]
