# Generated by Django 5.2.5 on 2026-01-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_heirassetselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='heirassetselection',
            name='wants_lottery',
            field=models.BooleanField(default=True, verbose_name='موافق على القرعة'),
        ),
    ]
