# Generated by Django 5.2.5 on 2026-01-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_heirassetselection_wants_lottery'),
    ]

    operations = [
        migrations.AddField(
            model_name='heir',
            name='allocated_share',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='القيمة المخصصة'),
        ),
        migrations.AddField(
            model_name='heirassetselection',
            name='selected_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='القيمة المختارة'),
        ),
        migrations.AddField(
            model_name='heirassetselection',
            name='status',
            field=models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('ACCEPTED', 'مقبول'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=20, verbose_name='حالة الاختيار'),
        ),
    ]
