# Generated by Django 5.2.4 on 2026-01-08 09:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_heir_allocated_share_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': 'القضية', 'verbose_name_plural': 'القضايا'},
        ),
        migrations.AlterField(
            model_name='case',
            name='case_number',
            field=models.CharField(max_length=50, verbose_name='رقم القضية'),
        ),
        migrations.AlterUniqueTogether(
            name='case',
            unique_together={('case_number', 'judge')},
        ),
    ]
