# Generated by Django 5.2.4 on 2026-02-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_alter_case_options_alter_case_case_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heir',
            name='blocking_reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='سبب الحجب'),
        ),
    ]
