# Generated by Django 6.0 on 2026-03-04 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_heir_blocking_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='وصف الجزء/العينة')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='القيمة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='cases.asset', verbose_name='الأصل التابع له')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_components', to='cases.heir', verbose_name='مخصص لـ')),
            ],
            options={
                'verbose_name': 'جزء من الأصل',
                'verbose_name_plural': 'أجزاء الأصول',
            },
        ),
    ]
