# Generated by Django 5.2.5 on 2026-03-12 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_assetcomponent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='is_liquidated',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='sold_price',
        ),
        migrations.RemoveField(
            model_name='heirassetselection',
            name='wants_lottery',
        ),
    ]
