# Generated by Django 5.2.5 on 2026-03-13 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_remove_asset_is_liquidated_remove_asset_sold_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicAssetListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=255, verbose_name='اسم البائع')),
                ('seller_email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('seller_phone', models.CharField(max_length=20, verbose_name='رقم التواصل')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='سعر العرض')),
                ('description', models.TextField(verbose_name='وصف العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط (يُعرض للبيع)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ العرض')),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='cases.assetcomponent', verbose_name='العينة/الأصل')),
            ],
            options={
                'verbose_name': 'عرض بيع أصل (عام)',
                'verbose_name_plural': 'عروض بيع الأصول (عامة)',
            },
        ),
    ]
