# Generated by Django 5.2.5 on 2026-03-14 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_publicassetlisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='heir',
            name='mutual_consent_status',
            field=models.CharField(choices=[('NOT_VOTED', 'لم يصوت'), ('AGREED', 'موافق على القسمة بالتراضي'), ('DISAGREED', 'غير موافق على القسمة بالتراضي')], default='NOT_VOTED', max_length=20, verbose_name='حالة التصويت للتراضي'),
        ),
        migrations.AddField(
            model_name='heirassetselection',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selection_intents', to='cases.assetcomponent', verbose_name='جزء الأصل'),
        ),
        migrations.AddField(
            model_name='heirassetselection',
            name='is_challenging_owner',
            field=models.BooleanField(default=False, verbose_name='نزاع ضد مالك حالي'),
        ),
        migrations.AddField(
            model_name='heirassetselection',
            name='pledge_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مبلغ التعهد الاضافي'),
        ),
        migrations.AddField(
            model_name='heirassetselection',
            name='requires_pledge',
            field=models.BooleanField(default=False, verbose_name='يتطلب تعهد مالي'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('PENDING', 'بانتظار القاضي'), ('ASSIGNED_TO_JUDGE', 'مقبولة (عند القاضي)'), ('WITH_CLERK', 'عند الكاتب (إدخال البيانات)'), ('DATA_REVIEW', 'مراجعة البيانات (عند القاضي)'), ('READY_FOR_CALCULATION', 'جاهزة للحساب'), ('SESSION_ACTIVE', 'جلسة توزيع التركة جارية'), ('CONSENT_PENDING', 'بانتظار موافقة الورثة (طلب تراضي)'), ('MUTUAL_SELECTION', 'مرحلة التراضي (اختيار الأصول)'), ('ALTERNATIVE_SELECTION', 'مرحلة الاعتراض (اختيار بديل)'), ('RAFFLE_PHASE', 'مرحلة القرعة للنزاعات'), ('PAYMENTS_PHASE', 'مرحلة السداد والتخارج (لوحة القاضي)'), ('COMPLETED', 'مكتملة')], default='PENDING', max_length=30, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='heir',
            name='acceptance_status',
            field=models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('ACCEPTED', 'موافق (انتهاء)'), ('REJECTED', 'غير موافق (اعتراض)')], default='PENDING', max_length=20, verbose_name='حالة القبول'),
        ),
        migrations.AlterField(
            model_name='heirassetselection',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selection_intents', to='cases.asset', verbose_name='الأصل'),
        ),
        migrations.CreateModel(
            name='DisputeRaffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='تم حل النزاع (إجراء القرعة)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.asset', verbose_name='الأصل المتنازع عليه')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='cases.case', verbose_name='القضية')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.assetcomponent', verbose_name='الجزء المتنازع عليه')),
                ('contenders', models.ManyToManyField(related_name='raffle_entries', to='cases.heir', verbose_name='المتنازعين')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_raffles', to='cases.heir', verbose_name='الفائز بالقرعة')),
            ],
            options={
                'verbose_name': 'نزاع / قرعة',
                'verbose_name_plural': 'النزاعات والقرعات',
            },
        ),
        migrations.CreateModel(
            name='PaymentSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('is_paid_to_judge', models.BooleanField(default=False, verbose_name='تم استلام المبلغ من قبل القاضي')),
                ('is_delivered_to_owner', models.BooleanField(default=False, verbose_name='تم تسليم المبلغ للمالك النهائي')),
                ('reason', models.CharField(max_length=255, verbose_name='سبب الدفعة (فرق قيمة، تعويض نزاع)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='cases.case', verbose_name='القضية')),
                ('original_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_expected', to='cases.heir', verbose_name='المستلم الأصلي (إن وجد)')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_owed', to='cases.heir', verbose_name='الدافع (المتعهد)')),
            ],
            options={
                'verbose_name': 'تسوية مالية',
                'verbose_name_plural': 'التسويات المالية',
            },
        ),
    ]
