# Generated by Django 5.2.5 on 2026-03-14 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_heir_mutual_consent_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='judge_consents_to_mutual',
            field=models.BooleanField(default=False, verbose_name='موافقة القاضي على القسمة بالتراضي'),
        ),
        migrations.AddField(
            model_name='heirassetselection',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='تم معالجته (تحويل لملكية أو نزاع)'),
        ),
        migrations.CreateModel(
            name='SelectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_text', models.TextField(verbose_name='نص الإجراء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإجراء')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_logs', to='cases.case', verbose_name='القضية')),
                ('heir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.heir', verbose_name='الوريث')),
            ],
            options={
                'verbose_name': 'سجل اختيار أصل',
                'verbose_name_plural': 'سجلات اختيار الأصول',
                'ordering': ['-created_at'],
            },
        ),
    ]
