# Generated by Django 5.2.5 on 2026-03-14 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_case_judge_consents_to_mutual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettlement',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.asset', verbose_name='الأصل المرتبط'),
        ),
        migrations.AddField(
            model_name='paymentsettlement',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.assetcomponent', verbose_name='الجزء المرتبط'),
        ),
        migrations.AddField(
            model_name='paymentsettlement',
            name='heir_confirmed_payment',
            field=models.BooleanField(default=False, verbose_name='قام الوريث بتأكيد السداد'),
        ),
    ]
