# Generated by Django 5.2.12 on 2026-03-18 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0018_paymentsettlement_asset_paymentsettlement_component_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentConflictRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'قيد المراجعة من الوريث1'), ('ACCEPTED', 'موافق (تم التنازل)'), ('RAFFLE_REQUIRED', 'مرفوض (طلب قرعة)')], default='PENDING', max_length=20, verbose_name='حالة الطلب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_conflicts', to='cases.case', verbose_name='القضية')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='cases.assetcomponent', verbose_name='العينة المطلوبة')),
                ('owner_heir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_conflicts', to='cases.heir', verbose_name='صاحب الأصل الأساسي (وريث 1)')),
                ('parent_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='cases.asset', verbose_name='الأصل المتنازع عليه')),
                ('requesting_heir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_conflicts', to='cases.heir', verbose_name='طالب العينة (وريث 2)')),
            ],
            options={
                'verbose_name': 'طلب نزاع على عينة',
                'verbose_name_plural': 'طلبات النزاع على العينات',
                'unique_together': {('component', 'requesting_heir')},
            },
        ),
    ]
