# Generated by Django 5.2.12 on 2026-03-18 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0019_componentconflictrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heir',
            name='acceptance_status',
            field=models.CharField(choices=[('PENDING', 'بانتظار القرعة'), ('ACCEPTED', 'مقبول'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=20, verbose_name='حالة القبول'),
        ),
        migrations.CreateModel(
            name='AllocationProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difference_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ الفرق للدفع')),
                ('status', models.CharField(choices=[('PENDING', 'بانتظار موافقة الوريث'), ('ACCEPTED', 'مقبول من الوريث'), ('REJECTED', 'مرفوض من الوريث')], default='PENDING', max_length=20, verbose_name='حالة الطلب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('assets', models.ManyToManyField(blank=True, to='cases.asset', verbose_name='الأصول المقترحة')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_proposals', to='cases.case', verbose_name='القضية')),
                ('components', models.ManyToManyField(blank=True, to='cases.assetcomponent', verbose_name='العينات المقترحة')),
                ('heir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_proposals', to='cases.heir', verbose_name='الوريث المستهدف')),
            ],
            options={
                'verbose_name': 'مقترح توزيع (بانتظار إقرار)',
                'verbose_name_plural': 'مقترحات التوزيع',
            },
        ),
    ]
