# Generated by Django 5.2.12 on 2026-03-19 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0020_alter_heir_acceptance_status_allocationproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationproposal',
            name='selected_settlement_ids',
            field=models.TextField(blank=True, null=True, verbose_name='معرفات التسويات المختارة'),
        ),
    ]
