# Generated by Django 5.2.12 on 2026-03-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0021_allocationproposal_selected_settlement_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='allow_heir_selection',
            field=models.BooleanField(default=True, verbose_name='السماح للورثة بالدخول لمرحلة الاختيار'),
        ),
    ]
