# Generated by Django 5.2.12 on 2026-03-22 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0022_case_allow_heir_selection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CASE_OPENED', 'فتح القضية'), ('INFO_UPDATED', 'تحديث بيانات'), ('ASSET_ADDED', 'إضافة أصل'), ('HEIR_ADDED', 'إضافة وريث'), ('PORTAL_OPENED', 'فتح بوابة الاختيار'), ('PORTAL_CLOSED', 'إغلاق بوابة الاختيار'), ('HEIR_SELECTION', 'اختيار وريث'), ('JUDGE_DECISION', 'قرار قاضي (قبول/رفض)'), ('RAFFLE_RESULT', 'نتيجة قرعة'), ('PAYMENT_CONFIRMED', 'تأكيد سداد نقدي'), ('FINAL_REPORT', 'اعتماد محضر القسمة النهائي'), ('OTHER', 'إجراء آخر')], max_length=50, verbose_name='نوع الإجراء')),
                ('description', models.TextField(verbose_name='تفاصيل الإجراء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ ووقت الإجراء')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='cases.case', verbose_name='القضية')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل القضية',
                'verbose_name_plural': 'سجلات القضايا',
                'ordering': ['-created_at'],
            },
        ),
    ]
