# Generated by Django 5.2.12 on 2026-03-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0023_caseauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heir',
            name='acceptance_status',
            field=models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('SUBMITTED', 'بانتظار مراجعة القاضي'), ('ACCEPTED', 'مقبول'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=20, verbose_name='حالة القبول'),
        ),
    ]
