# Generated by Django 5.2.12 on 2026-03-29 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0024_alter_heir_acceptance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentconflictrequest',
            name='is_full_asset',
            field=models.BooleanField(default=False, verbose_name='نزاع على أصل كامل'),
        ),
        migrations.AddField(
            model_name='disputeraffle',
            name='source',
            field=models.CharField(choices=[('MUTUAL_CONSENT', 'حالة التراضي'), ('PARTIAL_OBJECTION', 'الاعتراض الجزئي باختيار التركة')], default='MUTUAL_CONSENT', max_length=30, verbose_name='مصدر النزاع'),
        ),
        migrations.AlterField(
            model_name='componentconflictrequest',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='cases.assetcomponent', verbose_name='العينة المطلوبة'),
        ),
        migrations.AlterField(
            model_name='componentconflictrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'قيد المراجعة من الوريث1'), ('ACCEPTED', 'موافق (تم التنازل)'), ('RAFFLE_REQUIRED', 'مرفوض (طلب قرعة)'), ('CANCELED', 'ملغي (تم التنازل لطرف آخر)')], default='PENDING', max_length=20, verbose_name='حالة الطلب'),
        ),
        migrations.AlterField(
            model_name='heir',
            name='acceptance_status',
            field=models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('SUBMITTED', 'بانتظار مراجعة القاضي'), ('ACCEPTED', 'مقبول'), ('REJECTED', 'مرفوض'), ('OBJECTION_WITH_SELECTION', 'رفض مع اختيار تركتي')], default='PENDING', max_length=50, verbose_name='حالة القبول'),
        ),
    ]
