# Generated by Django 5.2.12 on 2026-03-30 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0025_componentconflictrequest_is_full_asset_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='componentconflictrequest',
            unique_together={('parent_asset', 'component', 'requesting_heir')},
        ),
    ]
