# Generated by Django 5.2.12 on 2026-03-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0026_alter_componentconflictrequest_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='heir',
            name='is_judge_confirmed',
            field=models.BooleanField(default=False, verbose_name='تم الاعتماد النهائي من القاضي'),
        ),
    ]
