# Generated by Django 5.2.12 on 2026-04-06 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0031_merge_20260404_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='estateobligationallocation',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obligation_allocations', to='cases.paymentsettlement', verbose_name='التسوية المالية المرتبطة'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('PENDING', 'بانتظار القاضي'), ('ASSIGNED_TO_JUDGE', 'مقبولة (عند القاضي)'), ('WITH_CLERK', 'عند الكاتب (إدخال البيانات)'), ('DATA_REVIEW', 'مراجعة البيانات (عند القاضي)'), ('READY_FOR_CALCULATION', 'جاهزة للحساب'), ('SESSION_ACTIVE', 'جلسة توزيع التركة جارية'), ('CONSENT_PENDING', 'بانتظار موافقة الورثة (طلب تراضٍ)'), ('MUTUAL_SELECTION', 'مرحلة التراضي (اختيار الأصول)'), ('ALTERNATIVE_SELECTION', 'مرحلة الاعتراض (اختيار بديل)'), ('RAFFLE_PHASE', 'مرحلة القرعة للنزاعات'), ('PAYMENTS_PHASE', 'مرحلة السداد والتخارج (لوحة القاضي)'), ('COMPLETED', 'مكتملة')], default='PENDING', max_length=30, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='caseauditlog',
            name='action',
            field=models.CharField(choices=[('CASE_OPENED', 'فتح القضية'), ('INFO_UPDATED', 'تحديث بيانات'), ('ASSET_ADDED', 'إضافة أصل'), ('HEIR_ADDED', 'إضافة وريث'), ('PORTAL_OPENED', 'فتح بوابة الاختيار'), ('PORTAL_CLOSED', 'إغلاق بوابة الاختيار'), ('HEIR_SELECTION', 'اختيار وريث'), ('JUDGE_DECISION', 'قرار قاضٍ (قبول/رفض)'), ('RAFFLE_RESULT', 'نتيجة قرعة'), ('PAYMENT_CONFIRMED', 'تأكيد سداد نقدي'), ('FINAL_REPORT', 'اعتماد محضر القسمة النهائي'), ('OTHER', 'إجراء آخر')], max_length=50, verbose_name='نوع الإجراء'),
        ),
    ]
