# Generated by Django 5.2.12 on 2026-04-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0032_estateobligationallocation_settlement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heir',
            name='acceptance_status',
            field=models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('SUBMITTED', 'بانتظار مراجعة القاضي'), ('ACCEPTED', 'مقبول'), ('REJECTED', 'مرفوض'), ('OBJECTION_WITH_SELECTION', 'رفض مع اختيار تركتي'), ('SELECTION_FINISHED', 'تم إكمال الاختيار اليدوي')], default='PENDING', max_length=50, verbose_name='حالة القبول'),
        ),
        migrations.AlterUniqueTogether(
            name='heirassetselection',
            unique_together={('heir', 'asset', 'component')},
        ),
    ]
