# Generated by Django 5.2.12 on 2026-04-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0033_alter_heir_acceptance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_sold_by_heir',
            field=models.BooleanField(default=False, verbose_name='مباع من قبل الوريث'),
        ),
        migrations.AddField(
            model_name='assetcomponent',
            name='is_sold_by_heir',
            field=models.BooleanField(default=False, verbose_name='مباع من قبل الوريث'),
        ),
    ]
