# Generated by Django 5.2.12 on 2026-04-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0034_asset_is_sold_by_heir_assetcomponent_is_sold_by_heir'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='سبب الرفض'),
        ),
    ]
