# Generated by Django 5.2.4 on 2026-04-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0035_case_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='inheritance_determination_doc',
            field=models.FileField(blank=True, null=True, upload_to='inheritance_docs/', verbose_name='صك حصر الورثة'),
        ),
    ]
