# Generated by Django 5.2.4 on 2026-04-21 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0036_case_inheritance_determination_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcomponent',
            name='parent_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_components', to='cases.assetcomponent', verbose_name='المكون الأب'),
        ),
    ]
