# Generated by Django 5.2.4 on 2026-04-21 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0037_assetcomponent_parent_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicassetlisting',
            name='asset',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='cases.asset', verbose_name='الأصل الكامل'),
        ),
        migrations.AddField(
            model_name='publicassetlisting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='listings/', verbose_name='صورة خاصة للعرض'),
        ),
        migrations.AlterField(
            model_name='publicassetlisting',
            name='component',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='cases.assetcomponent', verbose_name='العينة/الجزء'),
        ),
    ]
