# Generated by Django 5.2.4 on 2025-12-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_estate', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='إجمالي التركة')),
                ('net_estate', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='صافي التركة بعد الديون')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحساب')),
            ],
        ),
        migrations.CreateModel(
            name='HeirShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_fraction', models.CharField(max_length=20, verbose_name='النصيب الشرعي (كسر)')),
                ('share_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='النصيب (%)')),
                ('share_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='قيمة النصيب')),
            ],
        ),
    ]
