# Generated by Django 5.2.4 on 2025-12-02 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calculator', '0001_initial'),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationresult',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='cases.case', verbose_name='القضية'),
        ),
        migrations.AddField(
            model_name='heirshare',
            name='calculation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='calculator.calculationresult', verbose_name='الحساب'),
        ),
        migrations.AddField(
            model_name='heirshare',
            name='heir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='cases.heir', verbose_name='الوريث'),
        ),
    ]
